config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/account'

  get 'home/login'

  post 'home/attempt_login'

  get 'home/contact'

  get 'home/logout'

  # get 'admin', :to => 'access#menu'
  # get 'access/menu'
  # get 'access/login'
  # post 'access/attempt_login'
  # get 'access/logout'

	resources :users do
		member do
			get :delete
		end
	end

  resources :photos do 
    member do 
      get :delete
    end
  end
  # get 'users/new'

  # get 'users/edit'

  # get 'users/deactivate'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # in case of guest
    if user.has_role? :admin
      can :manage, :all
    else
      can :create, User
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
	belongs_to :user
  belongs_to :role
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :photos

	scope :sorted, lambda { order ("category ASC") }
end

app/models/image.rb
class Image < ApplicationRecord

	belongs_to :user
	belongs_to :category
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
end

app/models/photo.rb
class Photo < ApplicationRecord

	belongs_to :user
	belongs_to :category

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/role.rb
class Role < ApplicationRecord
	has_many :assignments
	has_many :users, :through => :assignments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password

	has_many :photos
	has_many :assignments
	has_many :roles, :through => :assignments, :dependent => :destroy
	
	has_attached_file :avatar, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100#" }, 
		default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :email, :presence => true,
										:length => { :maximum => 100 },
										:format => EMAIL_REGEX,
										:uniqueness => true

	validates :password, :presence => true,
											 :length => { :minimum => 6 }

	def has_role?(role_sym)
  	roles.any? { |r| r.role.underscore.to_sym == role_sym }
	end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	layout 'main'

	before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def menu
  end

  def login
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
  		found_user = User.where(:username => params[:username]).first
  		if found_user
  			authorized_user = found_user.authenticate(params[:password])
  		end
  	end

  	if authorized_user
  		session[:user_id] = authorized_user.id
  		session[:username] = authorized_user.username
  		flash[:notice] = 'User login successful!'
  		redirect_to(access_menu_path)
  	else
  		flash[:notice] = 'Login unsuccessful. Invalid username or password provided'
  		render('login')
  	end
  end

  def logout
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include CanCan::ControllerAdditions

  protect_from_forgery with: :exception

  private

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in."
      redirect_to(home_login_path)
      # redirect_to prevents requested action from running
    end
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout 'main'

  before_action :confirm_logged_in, :except => [:index, :login, :attempt_login, :logout]
	
  def index
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = 'User login successful!'
      redirect_to(home_account_path)
    else
      flash[:notice] = 'Login unsuccessful. Invalid username or password provided!'
      render('login')
    end
  end

  def account
    @user = User.find(session[:user_id])
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = 'Successfuly logged out!'
    redirect_to('/')
  end

  def contact
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  layout 'main'
  before_action :confirm_logged_in

  def index
  end

  def show
  end

  def new
    @categories = Category.sorted
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = "Photo successfully uploaded!"
      redirect_to(home_account_path)
    else
      flash[:notice] = "Error uploading photo!"
      render('new')
    end
  end

  def delete
  end

  def destroy
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :caption, :user_id, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource
  
  layout 'main'
  
  before_action :confirm_logged_in, :except => [:new, :create]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @role = Role.find_by_id(2) # Default to 'user' role
    @user.roles << @role
    if @user.save
      flash[:notice] = "User registration successfuly!"
      #redirect_to(user_path(:id => @user.id))
      redirect_to(root_path)
    else
      flash[:notice] = "Registration unsuccessful!"
      render('new')
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == session[:user_id]
      flash[:notice] = "Can not delete your own profile!"
      redirect_to(users_path)
    else 
      @user.avatar = nil
      @user.destroy
      redirect_to(users_path)
      flash[:notice] = "User deleted successfuly!"
    end
  end

  def deactivate
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :avatar, role_ids: [])
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def error_messages_for(object)
		render(:partial => 'application/error_messages', :locals => {:object => object})
	end

	def active_class(link_path)
  	current_page?(link_path) ? "active" : ""
 	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/attempt_login.html.erb
<h1>Access#attempt_login</h1>
<p>Find me in app/views/access/attempt_login.html.erb</p>

app/views/access/login.html.erb
<% @page_title = "User Login" %>
<div class="row">
	<div class="col-md-8">
    <p class="lead"></p>
		<div class="card">
			<div class="card-header">
		  	Please login below
		  </div>
		  <div class="card-block">
		  	<p class="card-text"></p>

				<%= form_tag(access_attempt_login_path, :method => :post) do %>
					<div class="form-group">
						<%= label_tag(:username) %>
						<%= text_field_tag(:username, params[:username], :class => 'form-control') %>
					</div>
					<div class="form-group">
						<%= label_tag(:password) %>
						<%= password_field_tag(:password, params[:password], :class => 'form-control') %>
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/access/logout.html.erb
<h1>Access#logout</h1>
<p>Find me in app/views/access/logout.html.erb</p>

app/views/access/menu.html.erb
<h1>Access#menu</h1>
<p>Find me in app/views/access/menu.html.erb</p>

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
	<div class="alert alert-danger" role="alert">
		<p>There were following errors:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/application/_footer.html.erb
	  <div class="footer">
	    <p>&copy; All rights reserved!</p>
	  </div>   
	</div><!-- .container -->  
  <%= javascript_include_tag('application') %>
</body>
</html>

app/views/application/_header.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="description" content="">
  <meta name="author" content="">
  <title>Podil | <%= @page_title || "Welcome to Podil" %></title>
  <%= stylesheet_link_tag('application', :media => 'all') %>
  <!-- Custom CSS -->
  <style>

  </style>

</head>
  <body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Podil</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= active_class(root_path) %>">
          <a class="nav-link" href="/">Home</a>
        </li>

        <% if session[:user_id] %>
        <li class="nav-item <%= active_class(home_account_path) %>">
          <%= link_to(home_account_path, :class => 'nav-link') do %>
            My Account 
          <% end %>
        </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About Us</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if session[:user_id] %>
          <li class="nav-item <%= active_class(new_photo_path) %>">
            <%= link_to 'Upload New Photo', new_photo_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', home_logout_path, :class => 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item <%= active_class(new_user_path) %>">
            <%= link_to 'Register', new_user_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item <%= active_class(home_login_path) %>">
            <%= link_to 'Sign In', home_login_path, :class => 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav> 

<!-- Page Content -->
<div class="container">

app/views/home/account.html.erb
<% @page_title = 'My Account' %>

<div class="jumbotron">
	<%= image_tag @user.avatar.url(:thumb), :class => 'img-thumbnail img-fluid float-left mr-2' %>
	<h1 class="display-4">Hello <%= @user.first_name %>!</h1>
	<p class="lead">Here are all your uploaded photos.</p>
	<hr class="my-4">
	<% @user.photos.each do |photo| %>
		<figure class="figure">
			<%= link_to photo_path(photo) do %> 
				<%= image_tag photo.image.url(:medium), :class => 'figure-img img-fluid rounded mr-4',
					:alt => photo.caption %>
			<% end %>
			<figcaption class="figure-caption"><%= photo.caption %></figcaption>
		</figure>
	<% end %>
</div>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<div class="row">
  <div class="col">
  <% @page_title = '' %>
    <div class="card">
      <div class="card-header">
        Welcome to Podil.
      </div>
      <div class="card-body">
        <div class="clearfix">
          <%= image_tag 'family.jpg', :class => 'figure-img img-fluid rounded float-right' %>
          <h2 class="card-title">Share your <span class="badge badge-info">life moments.</span></h2>
          <p class="card-text">Sign up and start uploading images.</p>
          <p class="card-text">Share with your friends and family.</p>
          <% if session[:user_id] %>
            <%= link_to 'Upload Photo', new_photo_path, :class => 'btn btn-primary' %>
            <%= link_to 'My Account', home_account_path, :class => 'btn btn-success' %>
          <% else %>
            <%= link_to 'Register', new_user_path, :class => 'btn btn-primary' %>
            <%= link_to 'Sign In', home_login_path, :class => 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/login.html.erb
<div class="row">
	<div class="col">
		<% @page_title = "User Login" %>

		<div class="card">
			<div class="card-header">
		  	Please login below
		  </div>
		  <div class="card-body">
		  	<p class="card-text"></p>

				<%= form_tag(home_attempt_login_path, :method => :post) do %>
					<div class="form-group">
						<%= label_tag(:username) %>
						<%= text_field_tag(:username, params[:username], :class => 'form-control', :required => true) %>
					</div>
					<div class="form-group">
						<%= label_tag(:password) %>
						<%= password_field_tag(:password, params[:password], :class => 'form-control', :required => true) %>
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podilror</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<%= render(:partial => 'application/header') %>
<p class="lead"></p>
<% if !flash[:notice].blank? %>
  <div class="row">
    <div class="col">
      <div class="alert alert-primary" role="alert">
        <%= flash[:notice] %>
      </div>
    </div>
  </div>
<% end %>

<%= yield %>

<%= render(:partial => 'application/footer') %>

app/views/photos/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group">
	<%= f.label(:category_id) %>
	<%= f.collection_select(:category_id, @categories, :id, :category, :class => 'form-control') %>
</div>
<div class="form-group">
  <%= f.label(:image) %>
  <%= f.file_field(:image, :class => 'form-control', :required => true) %>
</div>
<div class="form-group">
  <%= f.label(:caption) %>
  <%= f.text_field(:caption, :class => 'form-control', :required => true) %>
</div>  
  <%= f.hidden_field :user_id, :value => session[:user_id] %>

app/views/photos/delete.html.erb
<h1>Photos#delete</h1>
<p>Find me in app/views/photos/delete.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<div class="row">
	<div class="col">
		<% @page_title = "Upload photo" %>
    <p class="lead">Upload new photo!</p>
		<div class="card">
			<div class="card-header">
		  	Please fill the following form
		  </div>
		  <div class="card-body">
		  		
				<%= form_for @photo, :html => { :multipart => true } do |f| %>

					<%= render(:partial => 'form', :locals => {:f => f}) %>

					<button type="submit" class="btn btn-primary">Submit</button>

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group">
  <%= f.label(:avatar) %>
  <%= f.file_field(:avatar, :class => 'form-control', :required => true) %>

  <%= f.label(:first_name) %>
  <%= f.text_field(:first_name, :class => 'form-control', :required => true) %>

  <%= f.label(:last_name) %>
  <%= f.text_field(:last_name, :class => 'form-control', :required => true) %>

  <%= f.label(:email) %>
  <%= f.text_field(:email, :class => 'form-control', :required => true) %>

  <%= f.label(:username) %>
  <%= f.text_field(:username, :class => 'form-control', :required => true) %>

  <%= f.label(:password) %>
  <%= f.password_field(:password, :class => 'form-control', :required => true) %>

  <%= f.label(:password_confirmation) %>
  <%= f.password_field(:password_confirmation, :class => 'form-control', :required => true) %>
</div>

app/views/users/deactivate.html.erb
<h1>Users#deactivate</h1>
<p>Find me in app/views/users/deactivate.html.erb</p>

app/views/users/delete.html.erb
<% @page_title = "Delete User" %>

<div class="row">
  <%= form_for(@user, :method => 'delete') do |f| %>
		<div class="card">
			<div class="card-header">
				Are you sure you want to delete this user?
			</div>
		  <div class="card-block">
		  	<p class="card-text">
		  		<%= f.object.first_name + ' ' + f.object.last_name %> 
		  	</p>
		    <button type="submit" class="btn btn-primary">Submit</button>
		  </div>
		</div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% @page_title = "All users" %>
<div class="container">
	<% @users.each do |user| %>
		<div class="row">
			<div class="col-2">
				<%= image_tag user.avatar.url(:thumb) %>
			</div>
			<div class="col-6">
				<%= user.first_name + " " + user.last_name %><br>
				<%= user.email %>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<%= link_to("Edit", edit_user_path(user), :class => "btn btn-link") %>
				<%= link_to("Delete", delete_user_path(user), :class => "btn btn-link") %>
			</div>
		</div>
	<% end %>
</div>
		

app/views/users/new.html.erb
<% @page_title = "User Registration" %>
<div class="row">
	<div class="col">
	  <p class="lead">Register today and start sharing!</p>
		<div class="card help">
			<div class="card-header">
		  	Please fill the following form
		  </div>
		  <div class="card-body">
		  	<p class="card-text"></p>
		  		
				<%= form_for @user, :html => { :multipart => true } do |f| %>

					<%= render(:partial => 'form', :locals => {:f => f}) %>

					<button type="submit" class="btn btn-primary">Submit</button>

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% @page_title = "My Account" %>
<div class="container">
	<div class="row">
		<div class="col-2">
			<%= image_tag @user.avatar.url(:thumb) %>
		</div>
		<div class="col-6">
			<%= @user.first_name + " " + @user.last_name %><br>
			<%= @user.email %>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<%= link_to "My Photos", home_account_path, :class => "btn btn-link"  %>
			<%= link_to "Edit My Account", '#', :class => "btn btn-link" %>
		</div>
	</div>
</div>
		